version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - node_modules:/vue-app/node_modules

  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/rails-app
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  node_modules: 