version: "3"

services:
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/rails-app
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
